kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: jenkins-volume-claim
  nfs:
    server: 192.168.99.1
    path: /srv/nfs/k8s-dev-cluster/jenkins
