kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: sonar-volume-claim
  nfs:
    server: 192.168.99.1
    path: /srv/nfs/k8s-dev-cluster/sonar/
