apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http-server
  - protocol: TCP
    port: 50000
    targetPort: 50000
    name: remote-api
